version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: sqlite:latest  # Or use a volume for persistence

  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - flask-app
