global:
  scrape_interval: 5s  # How often Prometheus scrapes targets

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:8000']  # The container name and port
